import { useState } from "react";
import { api } from "../../api/client";
import { keys, useMutationWithInvalidation, useRequests } from "../../api/queries";

export function RequestReview() {
  const [filter, setFilter] = useState("");
  const [comments, setComments] = useState<Record<string, string>>({});
  const query = useRequests(filter || undefined);
  const review = useMutationWithInvalidation<{ id: string; status: "PENDING" | "APPROVED" | "REJECTED"; comment?: string }, unknown>(
    ({ id, ...body }) => api.patch(`/employees/requests/${id}/status`, body),
    [keys.requests, keys.vacations, ["dashboard", "recent-requests"], ["dashboard", "absenteeism"], keys.notifications],
  );
  return <div className="max-w-5xl mx-auto space-y-6"><div className="flex justify-between items-center"><h1 className="text-3xl font-extrabold">Révision des demandes</h1><select value={filter} onChange={(event) => setFilter(event.target.value)} className="p-2 rounded-xl border dark:bg-slate-800"><option value="">Toutes</option><option value="PENDING">En attente</option><option value="APPROVED">Approuvées</option><option value="REJECTED">Refusées</option></select></div><div className="space-y-4">{(query.data ?? []).map((request) => <div key={request.id} className="p-5 rounded-3xl bg-white dark:bg-slate-900 border dark:border-slate-800"><div className="flex justify-between gap-4"><div><div className="font-bold">{request.employee?.firstName} {request.employee?.lastName}</div><div className="text-sm text-slate-500">{request.requestType} · {request.detail}</div></div><span className="text-xs">{request.status}</span></div>{request.attachmentName ? <button onClick={async () => { const result = await api.get<{ url: string }>(`/employees/requests/${request.id}/attachment`); window.open(result.url, "_blank"); }} className="mt-3 text-sm text-blue-600">Voir le justificatif</button> : null}{request.status === "PENDING" ? <div className="mt-4"><textarea value={comments[request.id] ?? ""} onChange={(event) => setComments((items) => ({ ...items, [request.id]: event.target.value }))} className="w-full p-3 rounded-xl border dark:bg-slate-800" placeholder="Commentaire (obligatoire pour un refus)" /><div className="mt-3 flex justify-end gap-2"><button disabled={!comments[request.id]} onClick={() => review.mutate({ id: request.id, status: "REJECTED", comment: comments[request.id] })} className="px-4 py-2 rounded-xl bg-red-50 text-red-600 disabled:opacity-40">Refuser</button><button onClick={() => review.mutate({ id: request.id, status: "APPROVED", comment: comments[request.id] })} className="px-4 py-2 rounded-xl bg-emerald-600 text-white">Approuver</button></div></div> : null}{request.status === "APPROVED" && request.kind === "VACATION" ? <div className="mt-4 flex justify-end"><button disabled={review.isPending} onClick={() => review.mutate({ id: request.id, status: "PENDING", comment: "Demande rouverte pour révision" })} className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-2 text-sm font-semibold text-amber-700">Rouvrir la demande</button></div> : null}</div>)}</div></div>;
}
