export enum AlertType {
  ONBOARDING_DELAY = 'ONBOARDING_DELAY',
  DATA_QUALITY = 'DATA_QUALITY',
  AI_SECURITY = 'AI_SECURITY',
  SOCIAL_RISK = 'SOCIAL_RISK',
  DOCUMENT_MISSING = 'DOCUMENT_MISSING',
}
